import "./globals.css";
// import { Inter } from "next/font/google";
import { Francois_One, Fraunces } from "next/font/google";
import { ReactQueryClientProvider } from "@/utils/react-query";
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

const francois_one = Francois_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-francois-one",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={`${fraunces.className} ${francois_one.variable}`}>
        <ReactQueryClientProvider>
          <Navbar />
          {children}
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
